services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=admin456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgreslq/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=davyd2h@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
     - 5050:80
